GoogleMapsMVC.Web/Controllers/GMapsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoogleMapsMVC.Web.Controllers
{
    public class GMapsController : Controller
    {
        // GET: GMaps
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Save(decimal Latitude, decimal Longitude)
        {
            //TODO: Add code for saving to DB

            return Json(new { Status = "Success" });
        }
    }
}

GoogleMapsMVC.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoogleMapsMVC.Web.Controllers
{
    public class HomeController : Controller
    {
	   public ActionResult Index()
	   {
		  return View();
	   }

	   public ActionResult About()
	   {
		  ViewBag.Message = "Your application description page.";

		  return View();
	   }

	   public ActionResult Contact()
	   {
		  ViewBag.Message = "Your contact page.";

		  return View();
	   }
    }
}

GoogleMapsMVC.Web/Views/GMaps/Index.cshtml
@{
    ViewBag.Title = "Get Geo Location";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/GoogleMapsCss")

<div class="row">
    <h2>
        <div class="devsite-product-logo-container">
            <img src="https://www.gstatic.com/images/branding/product/1x/maps_64dp.png" class="devsite-product-logo" alt="Google Maps APIs">
        </div>
        Google Maps Geo Location
    </h2>
</div>
<br />
<br />
<div>
    <div class="row">
        <div class="col-md-4">
            <div class="row form-horizontal">
                <div class="form-group">
                    @Html.Label("Location: ", htmlAttributes: new { @class = "control-label col-md-1" })
                    <div class="col-md-10">
                        <input type="text" class="form-control fixControl" id="txtLocation" placeholder="Enter a location" />
                    </div>
                </div>
            </div>
            <div class="row form-horizontal">
                <div class="form-group">
                    @Html.Label("Latitude: ", htmlAttributes: new { @class = "control-label col-md-1" })
                    <div class="col-md-10">
                        <input type="text" class="form-control fixControl" id="txtLatitude" placeholder="Latitude" readonly />
                    </div>
                </div>
            </div>
            <div class="row form-horizontal">
                <div class="form-group">
                    @Html.Label("Longitude: ", htmlAttributes: new { @class = "control-label col-md-1" })
                    <div class="col-md-10">
                        <input type="text" class="form-control fixControl" id="txtLongitude" placeholder="Longitude" readonly />

                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-5">
                        <input type="button" class="form-control" id="btnSave" value="Save">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div id="map"></div>
        </div>
    </div>
</div>
<br />
<div id="infowindow-content">
    <img src="" width="16" height="16" id="place-icon">
    <span id="place-name" class="title"></span><br>
    <span id="place-address"></span>
</div>

@section scripts{

    @Scripts.Render("~/bundles/GoogleMapsCustom");
    <script>
        $(document).ready(function () {

            $("#btnSave").click(function () {

                if (txtLatitude.value != '' && txtLongitude.value != '') {

                    $.ajax({
                        url: '@Url.Action("Save", "GMaps")',
                        type: "POST",
                        dataType: "json",
                        data: {
                            Latitude: txtLatitude.value,
                            Longitude: txtLongitude.value
                        },
                        success: function (data) {
                            alert(data.Status);
                            if (data.Status === 'Success') {
                                document.getElementById('txtLatitude').value = '';
                                document.getElementById('txtLongitude').value = '';
                                document.getElementById('txtLocation').value = '';
                                document.getElementById('btnSave').classList.remove('btn-success');
                                document.getElementById('btnSave').disabled = true;
                            }
                        },
                        error: function (XMLHttpRequest, textStatus, errorThrown) {
                            //debugger;
                            alert(textStatus);
                        }
                    });
                }

            });
        });
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDmDZ1txsLQII-jXAYMIPPUtSl6QJm-GJA&libraries=places&callback=initMap">
    </script>
}

GoogleMapsMVC.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GoogleMapsMVC.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GoogleMapsMVC.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

GoogleMapsMVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>